config/routes.rb
Rails.application.routes.draw do
  resources :costs
  resources :incomes
  resources :categories
  devise_for :users
  root to: "categories#index"

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

end

app/models/cost.rb
class Cost < ActiveRecord::Base
  belongs_to :category, dependent: :destroy
  belongs_to :user, dependent: :destroy

  validates :amount,  numericality: { only_integer: true }

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = current_user.costs
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)
    @cost.user_id = current_user.id
    respond_to do |format|
      if @cost.save 
        if check_amount?(cost_params[:category_id])
          format.html { redirect_to @cost, flash:{ notice: 'Cost was successfully created.', error: 'you spending too much'}  }
          format.json { render :index, status: :created, location: @cost }
        else
          format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
          format.json { render :index, status: :created, location: @cost }
        end

      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        if check_amount?(cost_params[:category_id])
          format.html { redirect_to @cost, flash:{ notice: 'Cost was successfully created.', alert: 'you spending too much'}  }
          format.json { render :index, status: :created, location: @cost }
        else
          format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
          format.json { render :index, status: :created, location: @cost }
        end

      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:name, :description, :amount, :category_id)
    end

    def check_amount?(id)
      total_costs = current_user.categories.find(id).costs.map { |cost| cost.amount }.reduce(0, :+)
      total_incomes = current_user.categories.find(id).incomes.map { |income| income.amount }.reduce(0, :+) 
      if total_costs > total_incomes
        true
      else
        false
      end
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/views/costs/_form.html.erb
<%= form_for @cost, :html => { :class => "form-horizontal cost" } do |f| %>

    <% if @cost.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cost.errors.count, "error") %> prohibited this cost from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cost.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :category_id, options_for_select(current_user.categories.all.map { |cate|  [cate.name, cate.id ]}),{},{:class => 'form-control'} %>
    </div>
    <%= error_span(@cost[:category_id]) %>
  </div>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%= error_span(@cost[:amount]) %>
  </div>
  <div class="control-group" style="margin:10px 0px;">
    <div class="controls">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            costs_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/costs/edit.html.erb
<div class="row col-md-8 col-md-offset-2">
  <%- model_class = Cost -%>
  <div class="page-header">
    <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/costs/index.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th>Category</th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= link_to cost.id, cost_path(cost) %></td>
        <td><%= cost.name %></td>
        <td><%= cost.description %></td>
        <td><%= cost.category.name %></td>
        <td><%= number_to_currency( cost.amount, format: '%n %u')%></td>
        <td><%=l cost.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cost_path(cost), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cost_path(cost),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cost_path,
            :class => 'btn btn-primary' %>

app/views/costs/new.html.erb
<div class="row col-md-8 col-md-offset-2">
  <% if current_user.categories.count  == 0 %>
      <div class="alert alert-warning fade in">You don't have any Category, Please create category <%= link_to("create category", new_category_path)%></div>
  <% else %>
      <%- model_class = Cost -%>
      <div class="page-header">
        <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
      </div>
      <%= render :partial => 'form' %>
  <% end -%>
</div>

app/views/costs/show.html.erb
<%- model_class = Cost -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @cost.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @cost.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @cost.amount %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              costs_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cost_path(@cost), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cost_path(@cost),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>